### ISSUE TITLE
[API] Modify views to be insertable

### ISSUE THREAD

**Issue by PTKay** [i-on-project/codegarten#73]
Some views could be made compatible with INSERT statements in order to improve the `insertAndGet` method in the API code.

**Comment by dvsshadow** [comment]
Returning rows on view insertion does not return all of the values, namely auto-generated values, therefore we have two options:

- Getting the values from the view from the database side
- Getting the values from the separate tables from the application side

Since the latter is what is already being used, I think this issue doesn't deserve attention for now.
